### PR TITLE
Fix failing fixture test on Travis CI

### PR DESCRIPTION
**Pull request by felixbuenemann**
Instead of relying on binary comparison of the fixture png and the generated png, just parse and compare their headers.

This makes the test stable in the face of minor differences in the libpng versions used or metadata written by imagemagick.

### CODE REVIEW

**Comment by felixbuenemann** [comment]
Btw. if you think this is overkill it would also be possible to just extract and compare the relevant header bytes without parsing them. The parser code was adapted from the blog post [Binary pattern matching in Elixir with PNG parsing example](http://zohaib.me/binary-pattern-matching-in-elixir/).

**Comment by felixbuenemann** [comment]
This should be merged first, then I can rebase all other PR branches to make their tests pass.

**Comment by cloud8421** [comment]
Thanks, I've just seen all the PRs and good suggestions!

This looks fine and I agree, headers are enough. I'll merge it, so that other branches can be rebased as you said.

I'm currently on holiday for a week, I'll see if I can take a look at some of the other changes in the next few days, but most likely I'm gonna go through them next Sunday.

Thanks again!

**Comment by felixbuenemann** [comment]
@cloud8421 No rush, enjoy your holiday! I'll go ahead and rebase all the other PRs.

**Pull request merged**
